
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jake
 */
public class EmployeeHomePage extends javax.swing.JFrame {
    //declaration of model list to show jobs
DefaultListModel<Job> jobList = new DefaultListModel();
//creation of new login object.
login lgn  = new login();
    /**
     * Creates new form EmployeeHomePage
     * Will receive password from previous page
     */
    public EmployeeHomePage(int password) {
        initComponents();
        this.setLocationRelativeTo(null);
        loadJobs();    
        lgn.setPassword(password);
        
        
    }

    public EmployeeHomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadJobs();
        lgn.getPassword();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaJobDetails = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstJobs = new javax.swing.JList<>();
        lblJobList = new javax.swing.JLabel();
        lblJobDetails = new javax.swing.JLabel();
        btnSelectJob = new javax.swing.JButton();
        btnRental = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaJobDetails.setColumns(20);
        txaJobDetails.setRows(5);
        jScrollPane1.setViewportView(txaJobDetails);

        lstJobs.setModel(jobList);
        lstJobs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstJobsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstJobs);

        lblJobList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJobList.setText("Job List: ");

        lblJobDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJobDetails.setText("Details: ");

        btnSelectJob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSelectJob.setText("Select Job");
        btnSelectJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJobActionPerformed(evt);
            }
        });

        btnRental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRental.setText("Rentals");
        btnRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelectJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJobList)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(lblJobDetails)
                    .addComponent(btnRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobList)
                    .addComponent(lblJobDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectJob, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstJobsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstJobsValueChanged
        //This method has been created to select a job from the list and show the job details. 
         int index = lstJobs.getSelectedIndex();
    
    //if selected show details
         if(index > -1){
               Job job = jobList.getElementAt(index);
               txaJobDetails.setText(job.showJobDetails());
    }//GEN-LAST:event_lstJobsValueChanged
    }
    private void btnSelectJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJobActionPerformed
        // TODO add your handling code here:
       int  empID = lgn.getPassword();
        Job selectedJob = lstJobs.getSelectedValue();
        if(selectedJob != null){
                    DataIO data = new DataIO();
                    data.addEmpToJob(selectedJob.getJob_name(), empID);
                    JOptionPane.showMessageDialog(this, "You have selected " + selectedJob.getJob_name() + ".", "Added " + empID + " to job.", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnSelectJobActionPerformed

    private void btnRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalActionPerformed
    // TODO add your handling code here:
    new RentalHistory(lgn.getPassword()).setVisible(true);
    this.setVisible(false);
    this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
    this.dispose();
    }//GEN-LAST:event_btnRentalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRental;
    private javax.swing.JButton btnSelectJob;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJobDetails;
    private javax.swing.JLabel lblJobList;
    private javax.swing.JList<Job> lstJobs;
    private javax.swing.JTextArea txaJobDetails;
    // End of variables declaration//GEN-END:variables

    
    public void loadJobs(){
        try{
        DataIO data = new DataIO();
         ArrayList<Job> jobs = data.getJobs();

            //clear defaultlistmodel and text area
            jobList.clear();
            txaJobDetails.setText("");

            //copy each obj from the arraylist over to defauult list model
            
            for (int i = 0; i < jobs.size(); i++) {
                jobList.addElement(jobs.get(i));
            
            }
           }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    }

